### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by hugovk**
The [second Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0rc2-final-release-candidate-released/33105/5?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

---

Python 3.7 is EOL and no longer receiving security updates (or any updates) from the core Python team.

| version |  released  |    eol     |
|:--------|:----------:|:----------:|
| 3.11    | 2022-10-24 | 2027-10-24 |
| 3.10    | 2021-10-04 | 2026-10-04 |
| 3.9     | 2020-10-05 | 2025-10-05 |
| 3.8     | 2019-10-14 | 2024-10-14 |
| 3.7     | 2018-06-26 | 2023-06-27 |

https://devguide.python.org/versions/

---

Also upgraded Python syntax with https://github.com/asottile/pyupgrade `--py38-plus`.

### CODE REVIEW

**Comment by doronz88** [comment]
Do you know if this PR is expected to be merged? or if this python project is even still maintained?

**Comment by jonathanslenders** [comment]
Sorry, I don't want to drop Python 3.7 support yet, and 3.12 should already be supported. We might want to add 3.12 to the pipeline though.

@doronz88 : This project is definitely still maintained, but that doesn't mean there's activity every day.

**Comment by hugovk** [comment]
Sure, I've removed the commits dropping 3.7.

**Comment by jonathanslenders** [comment]
Hi @hugovk : Would you be able to rebase on master? I applied some changes because of Ruff, and because of that, some changes here are not relevant anymore.

**Comment by jonathanslenders** [comment]
Thanks!

**Comment by hugovk** [comment]
You're welcome!

**Pull request merged**
