### PR TITLE
RadioList: search

### PR DESCRIPTION
**Pull request by gpotter2**
This PR genually improves RadioList by:
- binding the escapekey to cancel
- adding support for the `pageup` and `pagedown` keys
- adds a search system, demonstrated below

[Prompt_toolkit RadioList.search v1](https://www.youtube.com/watch?v=RfzDHDBOqgA "Prompt_toolkit RadioList.search v1")

I'm of course open to any suggestions.

Note: I tried several implementations of the searching system. The first one aimed at adding `> [the text]` above or below the frame. However, due to how the scrolling is implemented, it was harder than expected, which is why I rolled-back to a simpler color-based searching system. I can elaborate if needed

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi,
Would you like me to split the PR ?

**Comment by jonathanslenders** [comment]
Hi @gpotter2,
That would be nice. If you can create a separate PR with only the page up/down changes, I can merge that already.

Notice that actually for a text area, page up/down also changes the scroll offset of the window. Pressing page-down keeps the cursor at the top of the window, and page-up keeps it at the bottom of the window. For now, I propose however to keep it like it is.

**Comment by gpotter2** [comment]
@jonathanslenders Here it is https://github.com/jonathanslenders/python-prompt-toolkit/pull/761
I've also reverted it from this PR.

Please tell me if you have in mind an implementation of a searching system that would fit better.

**Comment by gpotter2** [comment]
Hey ! Sorry for the ping, any news on such a thing ?

I understand you have little time for this, feel free to tell me any improvements/changes that should be done, or that you don't want to implement it that way for X reasons 😄

**Comment by gpotter2** [comment]
Closed for inactivity, and because it's going to conflict with too many things soon.

This could probably be integrated in a much more elegant way (using some internal functions / bindings to the existing search API ?)

**Pull request closed without merging**
