### PR TITLE
CheckboxList & more Dialogs doc

### PR DESCRIPTION
**Pull request by gpotter2**
Hey,

I've implemented what the TODO suggested. I've tested the code so it *should* work fine with existing implementations.

This PR:
- adds `CheckboxList`, which has a shared implementation with `RadioList`
- makes `Checkbox` use `CheckboxList`
- adds documentation about `radiolist_dialog` and `checkboxlist_dialog`
- adds a styling reference sheet to `docs/pages/dialogs.rst` to document the available styling classes + examples
- fixes missing `.run()` calls in the dialog examples from the doc, as of v3.0
- fixes typo in the doc: `frame-label` instead of `frame.label` as in the code:
 
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/237cf46ff50c8a689a72e3dfe664dfe69bffd245/prompt_toolkit/widgets/base.py#L415

The image linked to this example is the  wrong, as one style wasn't applied :/

#### Demo

- **Docs usage (with style)**: this is overly colored on purpose, as an example on how to use the style sheet. (Yeah it's somehow ugly)

This PR:
- fixes https://github.com/prompt-toolkit/python-prompt-toolkit/issues/890
- fixes https://github.com/prompt-toolkit/python-prompt-toolkit/issues/856

### CODE REVIEW

**Comment by gpotter2** [comment]
Off-topic question: how did you generate the graphics used [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/dialogs.html), for instance:

Fancy image I really wish I could generate too

I'd be happy to develop this part of the doc with `RadioList` and `CheckboxList`

**Comment by gpotter2** [comment]
Hi @jonathanslenders,

Now that https://github.com/prompt-toolkit/python-prompt-toolkit/pull/880 has been merged (great job by the way !), this should be ready for reviewing.

I've rebased & re-tested everything.

**Comment by jonathanslenders** [comment]
Hi @gpotter2,

Very nice. I like what you have. There are a few remarks however I added that need to be fixed before merging. It also needs to pass mypy, except for the "_ already defined warnings".

About the screenshots, I think I used the normal Terminal application on OS X, with some changes in the settings to not display anything in the title bar. Then I used the command-shift-4 screenshot to capture the Window. This will automatically create the shadow behind the window. The screenshots were made on a retina screen with a font size sufficiently big for the quality.

**Comment by gpotter2** [comment]
@jonathanslenders

> There are a few remarks however I added that need to be fixed before merging.

I'm sorry, I'm not sure what you mean :/
Is it a GitHub review you forgot to push ? I do that all the time :smile:

**Comment by gpotter2** [comment]
Sorry to bother. Any news on this ?

**Comment by jonathanslenders** [comment]
@gpotter2, I forgot indeed to submit the review. Thanks for reminding me!

**Comment by gpotter2** [comment]
Thanks for the follow up, I've updated the PR accordingly

**Comment by jonathanslenders** [comment]
Thank you @gpotter2, I really appreciate it!

**Comment by enbermudas** [comment]
Is there any documentation for this functionality?

**Comment by gpotter2** [comment]
There is but it looks like the automated readthedocs builds have been turned off: current version "master" is pretty old

You'll have to browse it  on GitHub: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/docs/pages/dialogs.rst

**Pull request merged**
