### PR TITLE
Support dumb terminals in PromptSession.

### PR DESCRIPTION
**Pull request by jonathanslenders**

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @halloleo,

Can you check this PR again? I believe both issues you mentioned in #1032 are now fixed.
I quickly tried in the Emacs inferior shell and it seems to run fine.

**Comment by halloleo** [comment]
Sure will do so. But it has to wait until next week when I'm back in the office.

**Comment by halloleo** [comment]
Yep, looks good. I've checked `confirmation-prompt.py` and other. Thanks a lot for this! :-)

**Comment by jonathanslenders** [comment]
Thank you @halloleo for testing!

**Comment by vale981** [comment]
Could this be merged please? 
See #390

**Pull request merged**
