### PR TITLE
Fix ctypes usage on pypy.

### PR DESCRIPTION
**Pull request by jonathanslenders**

### CODE REVIEW

**Comment by mgorny** [comment]
This works for me. Thank you!

**Comment by jonathanslenders** [comment]
Thanks for testing @mgorny!

**Comment by jonathanslenders** [comment]
@tornaria : Given that you contributed the original patch, can you confirm that this doesn't break the restoring of SIGINT?

**Comment by tornaria** [comment]
Tested, works fine, thank you.

**Comment by jonathanslenders** [comment]
Thank you!

**Pull request merged**
